### ISSUE TITLE
Back/forth mouse buttons don't work

### ISSUE THREAD

**Issue by blurred2426** [muslayev/iceweasel-win64#1]
Using Logitech MX Master 2S, back/forth mouse buttons do not work. Works normally in normal Firefox and Windows Explorer.

**Comment by muslayev** [comment]
set in about:config:

pref("mousebutton.4th.enabled", false);
pref("mousebutton.5th.enabled", false);

**Comment by V3T3RaN** [comment]
ЛYЛ, думл у миня аднаво таk ;-D

**Comment by muslayev** [comment]
> ЛYЛ, думл у миня аднаво таk ;-D

Удалю настройки в следующем билде.

**Comment by V3T3RaN** [comment]
okek =)
