### ISSUE TITLE
portable version missing

### ISSUE THREAD

**Issue by ydnmas** [muslayev/iceweasel-win64#10]
hello, in past releases there was a portable version of iceweasel that is missing in the current release, could you please add this?

**Comment by Alex9001** [comment]
I was about to make the same issue! Please Sir Muslayev grace us with a portable version.

**Comment by muslayev** [comment]
https://github.com/muslayev/iceweasel-win64/tree/master/portable

**Comment by Alex9001** [comment]
Confirmed working. Thank you very much for fast action and for maintaining these excellent browsers.
