### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by tutak-kat** [muslayev/iceweasel-win64#11]
Hi, are you gonna release portable version like Iceweasel-79.0?

**Comment by muslayev** [comment]
Hi, you can make portable version from here
https://github.com/muslayev/iceweasel-win64/tree/master/portable

**Comment by MikeBlueberry** [comment]
That's what I did, and it works. Thanks muslayev.

**Comment by tutak-kat** [comment]
Ok, I see it now thanks.
