### ISSUE TITLE
Your browser is managed by organisation

### ISSUE THREAD

**Issue by Marek33** [muslayev/iceweasel-win64#13]
Can you remove that in the next version, or can I somehow remove it?

When, it's enabled, I can't change a lot of things, like disabling the **Do Not Track** and which is worsts, a few great tweaks, which works on IceCat doesn't work on the Iceweasel, like the BuildID change.

Also, why mouse wheel doesn't work on it?

**Comment by muslayev** [comment]
These setting are controlled by [LibreWolf Settings Config](https://gitlab.com/librewolf-community/settings)
In root folder of Iceweasel you can find librewolf.cfg and change it as you want.

**Comment by Marek33** [comment]
Thanks, I found it! It was the: **defaultPref("general.autoScroll", false);**.

However, how can I disable the **your browser is managed by organisation**? I can't find that anywhere.

**Comment by muslayev** [comment]
Just ignore it or delete _distribution\policies.json_

**Comment by Marek33** [comment]
Thanks, deleting the **distribution\policies.json** worked!

Also, shouldn't be the **app.normandy. enabled** set to False and the toolkit.coverage to enabled, in the IceCat?

And the last question, will be their new Iceweaseal and IceCat releases, in the future?

**Comment by muslayev** [comment]
>Also, shouldn't be the app.normandy. enabled set to False and the toolkit.coverage to enabled, in the IceCat?
It depends on Icecat patchset. I dont make any changes, just build it.

>And the last question, will be their new Iceweaseal and IceCat releases, in the future?
All builds released according to the [Firefox Release Calendar](https://wiki.mozilla.org/Release_Management/Calendar)

**Comment by Marek33** [comment]
> > Also, shouldn't be the app.normandy. enabled set to False and the toolkit.coverage to enabled, in the IceCat?
> 
> It depends on Icecat patchset. I dont make any changes, just build it.

I understand, and thanks for the info!

> > And the last question, will be their new Iceweaseal and IceCat releases, in the future?
> 
> All builds released according to the [Firefox Release Calendar](https://wiki.mozilla.org/Release_Management/Calendar)

I'm glad to hear, that, and the https://github.com/muslayev/icecat-win64/issues/24 could be then closed, I guess.
