### ISSUE TITLE
Close/Minimize/Maximize does not theme

### ISSUE THREAD

**Issue by Alex9001** [muslayev/iceweasel-win64#14]
Hi, after updating to 81.0 the min/max/close buttons no longer theme.

I tried new profile but it is the same behavior.

Win10 x64

<img width="156" alt="sshot-1" src="https://user-images.githubusercontent.com/2770710/94353264-fb020100-0023-11eb-938e-f71321a3029c.png">

**Comment by muslayev** [comment]
as dublicate
