### ISSUE TITLE
Your browser is managed by an organization

### ISSUE THREAD

**Issue by Marek33** [muslayev/iceweasel-win64#16]
How do I remove this again? I forgot what the line was and since the old issue was deleted, I can't read, which line it was. Removing the librewolf.cfg doesn't help, and there is still some stuff locked. _Though, I don't get, why you don't use the Ghacks user file, instead of having just some parts of it, in the librewolf.cfg file. It would be surely better, since the Ghacks doesn't have a megabar, which makes me, you more fingerprintable, since the new Firefox probably doesn't have it (or at least, no update has activated it, for me)._

Also, why not just remove it, in the next update?

**Comment by muslayev** [comment]
\distribution\policies.json

**Comment by Marek33** [comment]
I see and thanks!
