### ISSUE TITLE
Portable exe no longer works

### ISSUE THREAD

**Issue by Alex9001** [muslayev/iceweasel-win64#20]
Hi, the browser no longer launches from start.exe with latest version update

Just nothing happens at all. If I copy my profile to %appdata% I can launch no problem, so not a profile problem.

Running Win10 x64

**Comment by muslayev** [comment]
hi. Rename firefox.exe to iceweasel.exe
Due to window theming bug, i no longer use the flag to change internal browser name.

**Comment by soyDESKTOP68A2MRFT** [comment]
man and if you compile nyxt for debian to windows???
https://nyxt.atlas.engineer/download
