### ISSUE TITLE
Is this a virus or a false positive, how do we know that this is safe when there's no source code?

### ISSUE THREAD

**Issue by Kame03** [muslayev/iceweasel-win64#22]
check out the virus scan results:

-virustotal
https://www.virustotal.com/gui/file/79418b2f64a51a95cf411a26b6fa771a1634aa61924b413cdd86c2730483235e

-hybrid analysis
https://www.hybrid-analysis.com/sample/79418b2f64a51a95cf411a26b6fa771a1634aa61924b413cdd86c2730483235e

**Comment by muslayev** [comment]
False positive. setup.exe was created with (https://nsis.sourceforge.io/Main_Page)[NSIS]
