### ISSUE TITLE
Can't view PDF inside browser

### ISSUE THREAD

**Issue by 3oheicrw** [muslayev/iceweasel-win64#24]
Only WebP is set to open inside browser. Both SVG and PDF are set to Always Ask and there is no options available allowed to view inside browser. On your icecat64 build it's normal like other Firefox allows viewing these formats inside browser but the rendering quality of PDF fonts is bad.

**Comment by 3oheicrw** [comment]
@muslayev Please add PDF and SVG reader back.

**Comment by muslayev** [comment]
> @muslayev Please add PDF and SVG reader back.

go to about:config and set true for 'pdfjs.disabled'

**Comment by 3oheicrw** [comment]
> > @muslayev Please add PDF and SVG reader back.
> 
> open about:config page and set false for 'pdfjs.disabled' or install SumatraPDF as alternative.

@muslayev Worked! SVG reader is always there, it's my mistake not check it before report because I think it's just like with PDF. BTW, why did you disabled pdfjs from the get go? Please consider let it on by default. Thanks :smile:

**Comment by muslayev** [comment]
Because built-in pdf client collects some telemetry data.
