### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by gerroon** [muslayev/iceweasel-win64#3]
Any plans for an updated version for Linux? I think the current icecat iss till at 60

**Comment by muslayev** [comment]
About linux build...no plans yet.
As i know, Icecat 68 will be release in July.

**Comment by gerroon** [comment]
Yeah it would be nice to have a privacy focued Linux version.

There is Librefox but somehow the development stopped and the devs did not respond for a while.

**Comment by BurnyBoi** [comment]
The team that makes Parabola GNU/Linux-Libre maintains a Linux version of Iceweasel:

https://www.parabola.nu/packages/libre/x86_64/iceweasel/

If you happen to be running Arch, you could very likely install this with pacman.

**Comment by gerroon** [comment]
@BurnyBoi

Thanks for letting me know. I am on Debian I will see if there is a compabilitypackage converter.
