### ISSUE TITLE
Can't render octicon

### ISSUE THREAD

**Issue by misaka00251** [muslayev/iceweasel-win64#4]
![image](https://user-images.githubusercontent.com/3908746/57533154-ab0f9500-736f-11e9-96f4-98b3aea76243.png)

`iceweasel-66.0.3.en-US.win64.installer.exe` don't have this issue.
OS: Windows 10 x64 1809

**Comment by misaka00251** [comment]
Update to `66.0.5` solved this. Thanks.

**Comment by muslayev** [comment]
Yes, i turned back google fonts ;)
