### ISSUE TITLE
Mp4 videos not showing up

### ISSUE THREAD

**Issue by gerroon** [muslayev/iceweasel-win64#5]
Hi

I cant get to see the embedded .mp4  videos, instead it says missing format or mime. I am thinking that this must be something about this branch. I am wondering if it is possible to enable to embbed videos, so the user can see them properly?

thanks

**Comment by muslayev** [comment]
hi.
Could you please provided the url of broken video?
Also, try this:
Go to Options -> Privacy & Secure -> Autoplay Settings, then set "Default for all websites" to "Allow audio and Video".

**Comment by muslayev** [comment]
not detected. ticket is closed.
