### ISSUE TITLE
Update privacy settings?

### ISSUE THREAD

**Issue by misaka00251** [muslayev/iceweasel-win64#7]
See privacytoolsIO/privacytools.io#1212, privacytoolsIO/privacytools.io#1430,  privacytoolsIO/privacytools.io#1704 & privacytoolsIO/privacytools.io#1834.

It seems that some of the settings in `settings.js` is outdated.

P.S. Since this repo is just a Firefox enhanced repo, I think we can change some of it :D

**Comment by muslayev** [comment]
Hi, currently i stopped supporting iceweasel

**Comment by muslayev** [comment]
will continue after a mounth.

**Comment by muslayev** [comment]
Done
