### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by ydnmas** [muslayev/iceweasel-win64#8]
I remember in past versions of iceweasel-win64, there would be a portable version but in verson 76.0, the portable version is missing. Could you add this?

**Comment by muslayev** [comment]
Hi, portable launcher for iceweasel needs to be rewritten, as i did it for icecat. Before i used bat_to_exe_converter, and most antiviruses detected it as malware. 

If i have a free time i will do it.

**Comment by muslayev** [comment]
Done

**Comment by petKitsune** [comment]
Thanks
